AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'Rakefile'
    - 'bin/**/*'
    
Documentation:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'app/models/**'
    - 'app/controllers/**'
    - 'app/mailers/**'
    - 'app/helpers/**'
    - 'app/policies/**'

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"
    - "config/routes.rb"
